import { z } from 'zod';

/**
 * Environment variable validation schema
 *
 * This file validates all environment variables at runtime using Zod.
 * - Runs at application startup (dev, build, test)
 * - Provides type-safe access to environment variables
 * - Fails fast with clear error messages for missing/invalid vars
 */

const envSchema = z.object({
  // Node Environment
  NODE_ENV: z
    .enum(['development', 'production', 'test'])
    .default('development'),

  // Database
  DATABASE_URL: z.string().url('DATABASE_URL must be a valid PostgreSQL URL'),
  TEST_DATABASE_URL: z
    .string()
    .url('TEST_DATABASE_URL must be a valid PostgreSQL URL')
    .optional(),

  // Email Configuration
  FROM_EMAIL: z.string().email('FROM_EMAIL must be a valid email address'),
  RESEND_API_KEY: z.string().min(1, 'RESEND_API_KEY is required'),

  // Application URLs
  NEXT_PUBLIC_APP_URL: z
    .string()
    .url('NEXT_PUBLIC_APP_URL must be a valid URL'),

  // Vercel Blob Storage
  BLOB_READ_WRITE_TOKEN: z.string().min(1, 'BLOB_READ_WRITE_TOKEN is required'),

  // Vercel OIDC (optional, auto-generated by Vercel)
  VERCEL_OIDC_TOKEN: z.string().optional(),

  // Next.js Telemetry (optional)
  NEXT_TELEMETRY_DISABLED: z.enum(['0', '1']).optional(),
});

/**
 * Validated and typed environment variables
 */
type Env = z.infer<typeof envSchema>;

/**
 * Parse and validate environment variables
 *
 * @throws {ZodError} If validation fails with detailed error messages
 */
function validateEnv(): Env {
  try {
    return envSchema.parse(process.env);
  } catch (error) {
    if (error instanceof z.ZodError) {
      const missingVars = error.errors
        .map((err) => `  - ${err.path.join('.')}: ${err.message}`)
        .join('\n');

      console.error(`❌ Invalid environment variables:\n${missingVars}`);
      throw new Error('Environment validation failed. Check your .env file.');
    }
    throw error;
  }
}

/**
 * Validated environment configuration
 *
 * Import this object to access type-safe environment variables:
 *
 * @example
 * ```ts
 * import { env } from '@/lib/config/env';
 *
 * const dbUrl = env.DATABASE_URL; // Type-safe and validated
 * ```
 */
export const env = validateEnv();

/**
 * Check if running in development mode
 */
export const isDevelopment = env.NODE_ENV === 'development';

/**
 * Check if running in production mode
 */
export const isProduction = env.NODE_ENV === 'production';

/**
 * Check if running in test mode
 */
export const isTest = env.NODE_ENV === 'test';

/**
 * Get the active database URL based on environment
 */
const getDatabaseUrl = (): string => {
  if (isTest && env.TEST_DATABASE_URL) {
    return env.TEST_DATABASE_URL;
  }
  return env.DATABASE_URL;
};
